nodeLinker: node-modules

npmPublishRegistry: "https://npm.nocturne.cash/"

npmScopes:
  midnight-ntwrk:
    npmAlwaysAuth: true
    npmPublishRegistry: "https://npm.nocturne.cash"
    npmRegistryServer: "https://npm.nocturne.cash"